version: '3.9'
services:
  api_category:
    container_name: api_category
    depends_on:
      - postgres_category
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    networks:
      - nw_api-category

  postgres_category:
    container_name: postgres_category
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - vol_postgres-category:/var/lib/postgresql/data/
    networks:
      - nw_api-category

networks:
  nw_api-category:
    driver: bridge

volumes:
  vol_postgres-category:
    driver: local
